# Generated by Django 6.0.7 on 2026-08-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="temperature_db",
            fields=[
                ("myid", models.AutoField(primary_key=True, serialize=False)),
                ("sensor_id", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="students",
        ),
    ]
